### ISSUE TITLE
각자 만든 파일들 하나의 서비스로 합쳐보기

### ISSUE THREAD

**Issue by sparta001** [sparta001/sparta_1_week#8]
문제점을 정리해 보아요.

**Comment by dongsub-joung** [comment]
문제점:
1. app.py의 셋팅이 혼잡해 있어서 뜻을 알고 정리해야하는데 플라스크에 대한 지식이 없다.
2. CSS에서 혼선이 생길 수도 있다. 이예지님이 프레임을 통일시켜줬는데 수정하려면 코드를 이해해야한다.
3. 개인적인 DB 연결이 안된다. 안전하게 셋팅된 DB로 연결해야한다. 개인의 디버깅이 제한되었다.

**Comment by dongsub-joung** [comment]
김대현님 db셋팅으로 로그인 페이지를 돌렸더니 생기는 에러:
pymongo.errors.ConfigurationError: The "dnspython" module must be installed to use mongodb+srv:// URIs. To fix this error install pymongo with the srv extra:

**Comment by dongsub-joung** [comment]
김대현님의 db셋팅으로 로그인을 돌렸을 때 생기는 에러:
AttributeError: module 'jwt' has no attribute 'ExpiredSignatureError'

정동섭님이 제대로 로그인 기능을 못 만드신듯 하다.

**Comment by dongsub-joung** [comment]
확인된 오류:
1. Pyjwt 미 설치로인한 오류
 2. utf-8형식에 대한 오류(2조에게서 들은 오류)
 > pw_hash = hashlib.sha256(password_receive.encode()).hexdigest()
